package fr.akshell.aoc.y2025;

import fr.akshell.aoc.base.BaseTest;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class Day7Test extends BaseTest<Long> {

    private static final String INPUT_DEMO_1 = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
""";
    private static final long INPUT_DEMO_1_PART1_RESULT = 21L;
    private static final long INPUT_DEMO_1_PART2_RESULT = 40L;
    private static final long FINAL_PART1_RESULT = 1662L;
    private static final long FINAL_PART2_RESULT = 40941112789504L;

    public Day7Test() {
        super(2025, 7, new Day7(),
                INPUT_DEMO_1, INPUT_DEMO_1_PART1_RESULT, INPUT_DEMO_1_PART2_RESULT,
                FINAL_PART1_RESULT, FINAL_PART2_RESULT);
    }
}
